name = "api"
compatibility_date = "2024-04-19"
node_compat = true

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "formbuild-skematics-d1"
database_id = "7e9b50b6-a904-42b1-a97c-229897877869"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"
